### ISSUE TITLE
Large marge at the right side of the slashed icons

### ISSUE THREAD

**Issue by alaindeurveilher** [nyon/fontawesome-actions#1]
Hi,
I just noticed a large marge at the right side of the slashed icons. I don't know if it is a technical limitation or if it's due to a copy paste error from the generate_combined_icons routine.
![fontawesome-actions-slash-icons-large-marge](https://cloud.githubusercontent.com/assets/5165564/7352936/e815696a-ed0f-11e4-9205-6e13e1d60d74.png)

It is a bit strange when aligning elements on the right side of a div to see this marge. We would expect the width of the icon to end with the max(x,y) of the slash bar.

Thank you very much.

**Comment by nyon** [comment]
Thanks for reporting. Should be fixed in v0.6.0. Please invalidate cache. If the problem still persist, please report.

**Comment by alaindeurveilher** [comment]
I tested and confirmed it's fixed in v0.6.0 :-)
Thank you.
