### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by saghul** [nyon/fontawesome-actions#13]
Hi there!

I've been using your project for a while, thanks for putting it together! ❤️ It's currently the only dependency I have which requires Bower for installation, as the rest (for me at least) use npm. Any chance you could put up a npm package as well?

Thanks a lot for your work!

**Comment by nyon** [comment]
Hi saghul,
I'll have a look at it tomorrow.

**Comment by saghul** [comment]
Hey, that was quick! Excellent, thanks a lot!

**Comment by nyon** [comment]
Added package.json and published newest fontawesome-actions version.
https://www.npmjs.com/package/fontawesome-actions
I don't know how you include the package in your project, so it would be nice if you could give me feedback whether it works as you expected.

Thanks for your interest.

**Comment by saghul** [comment]
Great! I'll give it a try later today and let you know. Cheers!

**Comment by saghul** [comment]
It worked perfectly!

I'm using it in combination with gulp, so I have the following in my index.html:

```
        <!-- build:css assets/styles/vendors.css -->
        <link rel="stylesheet" href="../node_modules/bootstrap-css-only/css/bootstrap.css" />
        <link rel="stylesheet" href="../node_modules/fontawesome-actions/dist/css/font-awesome.css" />
        <link rel="stylesheet" href="../node_modules/animate.css/animate.css" />
        <!-- endbuild -->
```

That will compress all those files into vendor.css with a simple gulp task:

```
gulp.task('css', function(){
    return gulp.src('src/*.html')
        .pipe(useref())
        .pipe(gulp.dest('www'));
});
```

Then the font can be copied using another simple task:

```
gulp.task('fonts', function() {
    gulp.src('node_modules/fontawesome-actions/dist/fonts/*')
        .pipe(gulp.dest('www/assets/fonts'));
});
```

So this really helped me out, since I could ditch Bower.  Not that I have anything against it, but since I already need npm, might as well just use a single package manager :-)

Cheers!
