### ISSUE TITLE
For some reason fa-user-circle is not working

### ISSUE THREAD

**Issue by contentfree** [nyon/fontawesome-actions#14]
Not sure if this is because of the combinations but it's apparently removing icons from Font Awesome.

**Comment by nyon** [comment]
Could you try to clear your cache and reload your page? It's working fine for me.

**Comment by contentfree** [comment]
I installed the gem from rails assets, ala

```
source 'https://rails-assets.org' do
  gem 'rails-assets-fontawesome-actions'
end
```

Then I `bundle`d. This installed the gem `rails-assets-fontawesome-actions-0.12.1`. Looking in that gem's files, `app/assets/stylesheets/fontawesome-actions/font-awesome.scss` does not include `fa-user-circle`.

What am I missing?

**Comment by nyon** [comment]
Ok, you're not missing anything. I forgot to add a tag to the newest version of this package. Fixed the problem. rails-assets should receive the new version in a few minutes.

**Comment by nyon** [comment]
Should be fixed now. Please try again and tell me, if it works.

**Comment by contentfree** [comment]
Fixed. Thanks.
