### ISSUE TITLE
fa-nfc

### ISSUE THREAD

**Issue by 2ndGAB** [nyon/fontawesome-actions#17]
Hello,
It seems that fa-nfc requested from 2013 to font-awesome is not ready to be available. 
Maybe some rights problems.
Anyway it seems this [one](http://www.free-icons-download.net/nfc-sign-icon-61052/) is free...

**Comment by nyon** [comment]
That is a good idea, but this repository is about combining existing icons. I do not create new icons. Please +1 the request in the FontAwesome repository.
