### ISSUE TITLE
fa-trash

### ISSUE THREAD

**Issue by cyrilchapon** [nyon/fontawesome-actions#19]
`fa-trash` is not a stupid idea neither, it would add another options to "delete" stuff

**Comment by nyon** [comment]
fa-trash is already added as an operator. see for example fa-heart-o-trash:

![image](https://user-images.githubusercontent.com/3247445/27389744-8da75870-569f-11e7-9384-511b996929da.png)

for trashing your favorite

**Comment by cyrilchapon** [comment]
Oh sorry for this. I searched for 'bin'
👍
