### ISSUE TITLE
fa-slash

### ISSUE THREAD

**Issue by caBBAlainB** [nyon/fontawesome-actions#2]
Hello,
Does the possibility to fa-xxxx-slash available for all icons or for some defined icons only?

Alain

**Comment by nyon** [comment]
You can extend the icon set by yourself. A contributing guideline is in the readme.
If you could tell me, what icon you need, I could extend the icon set for you and upload a new version. fa-xxx-slash is currently only available for the following icons:

fa-comment-slash
fa-picture-o-slash
fa-folder-open-slash
fa-tags-slash
fa-folder-slash
fa-heart-slash
fa-cube-slash
fa-tag-slash
fa-envelope-slash
fa-user-slash
fa-file-slash
fa-folder-o-slash
fa-calendar-slash
fa-shopping-cart-slash
fa-file-text-slash
fa-cloud-slash
fa-folder-open-o-slash
fa-group-slash
fa-file-text-o-slash
fa-file-code-o-slash
fa-file-video-o-slash
fa-bookmark-slash
fa-file-zip-o-slash
fa-file-image-o-slash
fa-file-powerpoint-o-slash
fa-file-excel-o-slash
fa-file-word-o-slash
fa-heart-o-slash
fa-filter-slash
fa-file-audio-o-slash
fa-camera-slash
fa-inbox-slash
fa-link-slash
fa-video-camera-slash
fa-floppy-o-slash
fa-file-pdf-o-slash
fa-database-slash

**Comment by caBBAlainB** [comment]
Hi,
Thanks for your answer.
In fact I'm interested by fa-globe to indicate online/offline status, but maybe fa-cloud could do the trick.

Anyway I have another problem because I even cannot display fa-folder-slash.
Is there something missing on my install ??

I installed it with bower and then linked like files below:
font-awesome.min.css -> ../../components/fontawesome-actions/dist/css/font-awesome.min.css

FontAwesome.otf -> ../../components/fontawesome-actions/dist/fonts/FontAwesome.otf
fontawesome-webfont.eot -> ../../components/fontawesome-actions/dist/fonts/fontawesome-webfont.eot
fontawesome-webfont.svg -> ../../components/fontawesome-actions/dist/fonts/fontawesome-webfont.svg
fontawesome-webfont.ttf -> ../../components/fontawesome-actions/dist/fonts/fontawesome-webfont.ttf
fontawesome-webfont.woff -> ../../components/fontawesome-actions/dist/fonts/fontawesome-webfont.woff
fontawesome-webfont.woff2 -> ../../components/fontawesome-actions/dist/fonts/fontawesome-webfont.woff2

I tried fa-cloud-slash but I get a chineese character instead:

![2015-05-12 12_30_21-pros_agthemes](https://cloud.githubusercontent.com/assets/9322571/7585089/dc507298-f8a2-11e4-86f9-f0d9239b69ee.png)

**Comment by nyon** [comment]
Could you try to disable the cache or do a "shift + reload" in your browser? I guess its using the cached version of the "old" font-awesome.
The fact that it displays a asian character means that the css is linked properly, so there has to be a problem with the font itself.

PS: I will add fa-globe-slash today

**Comment by caBBAlainB** [comment]
Exactly, it was a cache problem. And many thanks for your job, it's very usefull!

**Comment by nyon** [comment]
Added fa-globe in version 0.7.0.

**Comment by caBBAlainB** [comment]
Cool, many thanks
