### ISSUE TITLE
missing fa-map

### ISSUE THREAD

**Issue by caBBAlainB** [nyon/fontawesome-actions#3]
Hello,
I think I'm up to date and it seems fa-map is missing. Do you confirm?

Regards,
Alain

**Comment by alaindeurveilher** [comment]
Are you sure you used it correctly ? Because fa-map is really there in v4.4.0: http://fortawesome.github.io/Font-Awesome/icon/map/

**Comment by nyon** [comment]
fa-map is missing since it was included in 4.4+. fontawesome-actions currently only imports 4.3. I'll fix that and upload a new version asap.

**Comment by alaindeurveilher** [comment]
Ooops, sorry for my reply earlier, I did not realise it was about fontawesome**-actions**, I thought we were in the github of fontawesome :-p

**Comment by caBBAlainB** [comment]
Ok, perfect.
nop AlainD

**Comment by nyon** [comment]
Sorry for the delay, updated fontawesome to the current version (4.4.0). So fa-map should be included now.
Please open a new issue for things like fa-map-add.
