### ISSUE TITLE
user-plus is redundant

### ISSUE THREAD

**Issue by My1** [nyon/fontawesome-actions#4]
well title says it all.

in the css line 1799 character \f234 and another one on line 2212 character \f3b9
both use the same class which might easily lead to problems...

**Comment by My1** [comment]
"2,115 additions, 1,979 deletions not shown" in the CSS? was so much stuff implemented multiple times?

**Comment by nyon** [comment]
Deleted:
- envelope-o
- file-o
- bookmark-o
- comment-o
- folder-o
- user-plus

Somehow git marks the appendix part of fontawesome-actions as deleted and then added. Perhaps I need to add spaces between the css rules.

**Comment by My1** [comment]
well it is weird, maybe you find some way since it looks quite shocking as it's pretty much the half CSS that was completely rewritten....
