### ISSUE TITLE
Problème avec fa-map

### ISSUE THREAD

**Issue by 2ndGAB** [nyon/fontawesome-actions#7]
Hello nyon,

I've just updated font-awesome action but I cannot display fa-map... icons
Other icons work well so I don't understand why these ones don't work.
Any idea?

**Comment by nyon** [comment]
Have you tried to invalidate your cache? Try to append a version string to your CSS file:
fontawesome.css?version=83e23c3

Could you provide a live example, so that I am able to debug it?

**Comment by 2ndGAB** [comment]
Sorry,
I discoverd a bad link in my file system :-(

**Comment by nyon** [comment]
No problem.
