### ISSUE TITLE
file-text-o / file-text as a new overlay for all

### ISSUE THREAD

**Issue by KyleFairns** [nyon/fontawesome-actions#9]
The file would represent lists or details (at least, that's how we plan on using it), which would be extremely useful, as we already use the cogs for general settings of the icons that we use (as for user, to give an example).

Would you be able to implement this?

**Comment by tagliala** [comment]
Sorry I didn't get this request, could you please clarify?

**Comment by nyon** [comment]
Sorry for the late reply, github did not notify me of this (or my email spam filter crunched it up). Of course I can add it as an operator (meaning putting it in the lower right corner of a base icon). I'll update the repository in a few days.
